from src.core.config import get_settings
from src.database.models import (
    ActivationTokenModel,
    Base,
    CartItemModel,
    CartModel,
    CertificationModel,
    CommentLikeModel,
    DirectorModel,
    GenderEnum,
    GenreModel,
    MovieCommentModel,
    MovieFavoriteModel,
    MovieModel,
    MovieRatingModel,
    MovieReactionEnum,
    MovieReactionModel,
    MoviesDirectorsModel,
    MoviesGenresModel,
    MoviesStarsModel,
    OrderItemModel,
    OrderModel,
    OrderStatusEnum,
    PaymentItemModel,
    PaymentModel,
    PaymentStatusEnum,
    PasswordResetTokenModel,
    RefreshTokenModel,
    StarModel,
    UserGroupEnum,
    UserGroupModel,
    UserModel,
    UserProfileModel,
)


if get_settings().DATABASE_TYPE == "sqlite":
    from src.database.session_sqlite import (
        get_sqlite_db as get_db,
        get_sqlite_db_contextmanager as get_db_contextmanager,
        sqlite_engine as engine,
    )
else:
    from src.database.session_postgresql import (
        get_postgresql_db as get_db,
        get_postgresql_db_contextmanager as get_db_contextmanager,
        postgresql_engine as engine,
    )


__all__ = [
    "engine",
    "get_db",
    "get_db_contextmanager",
    "ActivationTokenModel",
    "Base",
    "CartItemModel",
    "CartModel",
    "CertificationModel",
    "CommentLikeModel",
    "DirectorModel",
    "GenderEnum",
    "GenreModel",
    "MovieCommentModel",
    "MovieFavoriteModel",
    "MovieModel",
    "MovieRatingModel",
    "MovieReactionEnum",
    "MovieReactionModel",
    "MoviesDirectorsModel",
    "MoviesGenresModel",
    "MoviesStarsModel",
    "OrderItemModel",
    "OrderModel",
    "OrderStatusEnum",
    "PaymentItemModel",
    "PaymentModel",
    "PaymentStatusEnum",
    "PasswordResetTokenModel",
    "RefreshTokenModel",
    "StarModel",
    "UserGroupEnum",
    "UserGroupModel",
    "UserModel",
    "UserProfileModel",
]
